server:
  port: 3000
  servlet:
    context-path: /cadastros/cervejas

spring:
  application:
    name: cadastro-cerveja-service
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/brewery
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
  main:
    banner-mode: off
  flyway:
    locations:
    - classpath:db/migrations
